-include enc.dep
enc.lo: /workspace/enc.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/workspace $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /workspace/enc.c -o enc.lo  -MMD -MF enc.dep -MT enc.lo
$(phplibdir)/enc.la: ./enc.la
	$(LIBTOOL) --tag=CC --mode=install cp ./enc.la $(phplibdir)

./enc.la: $(shared_objects_enc) $(ENC_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_enc) $(ENC_SHARED_LIBADD)

